### ISSUE TITLE
CreditCardFormatter doesn't work correct with test UnionPay card

### ISSUE THREAD

**Issue by ursasoft** [barbarity/CreditCardFormatter#4]
"6200 0000 0000 0005" is returned as invalid credit card number

**Comment by barbarity** [comment]
Hi @sebasx,

This is probably my mistake for not updating the README. Please make sure that you're using the correct formatters. China UnionPay isn't included in the default list of formatters.

To add it you can use all formatters like this:

```swift
let creditCardFormatter = CreditCardFormatter()
creditCardFormatter.formatters = CreditCardFormatters.all
creditCardFormatter.isValid("6200 0000 0000 0005") // returns true
